version: '3'

services:
  template_name_service:
    image: template_name_image:latest
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: template_name_container
    volumes:
      - .:/template_name_volume
    ports:
      - "8001:8000"
